pa036_social_network:
    resource: "@PA036SocialNetworkBundle/Controller/"
    type:     annotation
    prefix:   /

account:
    resource: "@PA036AccountBundle/Controller/"
    type:     annotation
    prefix:   /

