security:
    encoders:
      PA036\AccountBundle\Entity\User:
                  algorithm: bcrypt
                  iterations: 13

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        # ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
      users:
            entity: { class: PA036AccountBundle:User, property: email }

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        login:
            pattern:  ^/login$
            anonymous:  ~
            security: true
         
        register:
            pattern:   ^/register
            anonymous: ~
            security: false
              
        secured_area:
            pattern:    ^/
            form_login:
                check_path: login_check
                login_path: login
                success_handler: security.authentication.login_success_handler
            logout:
                path:   logout
                target: login
                invalidate_session: false
            anonymous: true
            #http_basic:
            #    realm: "Secured Demo Area"

    access_control:
        - { path: ^/login$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: ROLE_USER}
